include(CMakeParseArguments)

function(SbeCodeGenRemoveMatchesFromList)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs MATCHES)
    cmake_parse_arguments(TQ_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (_scg_LIST ${_scg_PARSED_UNPARSED_ARGUMENTS})
        foreach (_scg_ENTRY ${${_scg_LIST}})
            foreach (_scg_MATCH ${_scg_PARSED_MATCHES})
                if (${_scg_ENTRY} MATCHES ${_scg_MATCH})
                    list(REMOVE_ITEM ${_scg_LIST} ${_scg_ENTRY})
                endif()
            endforeach()
        endforeach()
        set(${_scg_LIST} ${${_scg_LIST}} PARENT_SCOPE)
    endforeach()
endfunction()

function(SbeCodeGenAddTestsFromSourceList)
    set(options)
    set(oneValueArgs PREFIX)
    set(multiValueArgs LIBS OPTIONS DEFINITIONS)

    cmake_parse_arguments(_scg_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (_scg_LIST ${_scg_PARSED_UNPARSED_ARGUMENTS})
        foreach (_scg_ENTRY ${${_scg_LIST}})
            if (${_scg_ENTRY} MATCHES ".*_test.cpp")
                string(REGEX REPLACE "^.*\/(.*)_test\.cpp$" "\\1" testName "${_scg_ENTRY}")
                set(testName "${_scg_PARSED_PREFIX}-${testName}-test")

                message(STATUS "found test \"${testName}\"")

                add_executable(${testName} ${_scg_ENTRY})
                target_compile_options(${testName} PRIVATE ${_scg_PARSED_OPTIONS})
                target_compile_definitions(${testName} PRIVATE ${_scg_PARSED_DEFINITIONS})
                target_link_libraries(${testName} PRIVATE ${_scg_PARSED_LIBS})

                add_test(${testName} ${testName})
            endif()
        endforeach()
    endforeach()
endfunction()

function(SbeCodeGenAddBenchmarksFromSourceList)
    set(options)
    set(oneValueArgs PREFIX)
    set(multiValueArgs LIBS COMPILE_OPTIONS LINK_OPTIONS DEFINITIONS)

    cmake_parse_arguments(_scg_PARSED "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    foreach (_scg_LIST ${_scg_PARSED_UNPARSED_ARGUMENTS})
        foreach (_scg_ENTRY ${${_scg_LIST}})
            if (${_scg_ENTRY} MATCHES ".*_bm.cpp")
                string(REGEX REPLACE "^.*\/(.*)_bm\.cpp$" "\\1" benchmarkName "${_scg_ENTRY}")
                set(benchmarkName "${_scg_PARSED_PREFIX}-${benchmarkName}-bm")

                add_executable(${benchmarkName} ${_scg_ENTRY})
                target_compile_options(${benchmarkName} PRIVATE ${_scg_PARSED_COMPILE_OPTIONS})
                target_compile_definitions(${benchmarkName} PRIVATE ${_scg_PARSED_DEFINITIONS})
                target_link_options(${benchmarkName} PRIVATE ${_scg_PARSED_LINK_OPTIONS})
                target_link_libraries(${benchmarkName} PRIVATE ${_scg_PARSED_LIBS})
            endif()
        endforeach()
    endforeach()
endfunction()

function(SbeCodeGenExcludeTestsAndBenchmarksFromSourceList _scg_LIST)
    list(FILTER ${_scg_LIST} EXCLUDE REGEX ".*_test.cpp")
    list(FILTER ${_scg_LIST} EXCLUDE REGEX ".*_bm.cpp")
    set(${_scg_LIST} ${${_scg_LIST}} PARENT_SCOPE)
endfunction()
